name: idomuss
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter
  location: ^3.0.2
  http: ^0.12.0
  firebase_admin: ^0.1.3
  google_sign_in: ^4.4.4
  firebase_database: ^3.1.5
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.14.0+5
  provider: ^3.1.0
  flutter_spinkit: ^4.1.2
  cupertino_icons: ^0.1.2
  email_validator: ^1.0.0
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: "^0.0.1"
  mask_text_input_formatter: ^1.0.6
  cpfcnpj: ^1.0.3
  image_picker: ^0.6.7+1
  curved_navigation_bar: ^0.3.2
  firebase_storage: ^3.1.6
  carousel_slider: ^2.1.0
  page_transition: ^1.1.4
  flutter_time_picker_spinner: ^1.0.6+1
  awesome_dialog: ^1.2.0
  google_maps_flutter: ^0.5.25+1
  geolocator: ^6.0.0+4
  geocoding: ^1.0.3+1
  search_cep: ^3.0.0+2


flutter_launcher_name:
  name: "Idomuss"

flutter_icons:
  image_path: "assets/geral/ic_launcher.png"
  ios: true
  android: true


dev_dependencies:

  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/onboarding/
   - assets/geral/
   - assets/status/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 900
          
  
  
